services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mongo-data:
